"""App Settings"""

# Django
from django.conf import settings

WIZARDINDUSTRY_SETTING_ONE = getattr(settings, "WIZARDINDUSTRY_SETTING_ONE", None)
WIZARDINDUSTRY_BLUEPRINT_SCOPE = getattr(settings, "WIZARDINDUSTRY_BLUEPRINT_SCOPE", "esi-characters.read_blueprints.v1")
WIZARDINDUSTRY_CORPORATION_BLUEPRINT_SCOPE = getattr(settings, "WIZARDINDUSTRY_CORPORATION_BLUEPRINT_SCOPE", "esi-corporations.read_blueprints.v1")
WIZARDINDUSTRY_BLUEPRINT_SYNC_ENABLED = getattr(settings, "WIZARDINDUSTRY_BLUEPRINT_SYNC_ENABLED", True)
WIZARDINDUSTRY_ESI_COMPATIBILITY_DATE = getattr(settings, "WIZARDINDUSTRY_ESI_COMPATIBILITY_DATE", "2026-03-06")
WIZARDINDUSTRY_BLUEPRINT_SYNC_CYCLE_HOURS = getattr(settings, "WIZARDINDUSTRY_BLUEPRINT_SYNC_CYCLE_HOURS", 24)
WIZARDINDUSTRY_BLUEPRINT_SYNC_MAX_PER_RUN = getattr(settings, "WIZARDINDUSTRY_BLUEPRINT_SYNC_MAX_PER_RUN", 25)
WIZARDINDUSTRY_CORPORATION_BLUEPRINT_SYNC_ENABLED = getattr(settings, "WIZARDINDUSTRY_CORPORATION_BLUEPRINT_SYNC_ENABLED", True)
WIZARDINDUSTRY_CORPORATION_BLUEPRINT_SYNC_CYCLE_HOURS = getattr(settings, "WIZARDINDUSTRY_CORPORATION_BLUEPRINT_SYNC_CYCLE_HOURS", 24)
WIZARDINDUSTRY_CORPORATION_BLUEPRINT_SYNC_MAX_PER_RUN = getattr(settings, "WIZARDINDUSTRY_CORPORATION_BLUEPRINT_SYNC_MAX_PER_RUN", 10)
