# Generated by Django 4.2.13 on 2024-09-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wizardindustry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseprice",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
