# Generated by Django 4.2.13 on 2024-09-11 10:13

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveuniverse", "0010_alter_eveindustryactivityduration_eve_type_and_more"),
        ("wizardindustry", "0003_remove_baseprice_price_baseprice_base_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="invMetaTypes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_type_id", models.IntegerField(blank=True, null=True)),
                ("meta_group_id", models.IntegerField(blank=True, null=True)),
                (
                    "eve_type",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inv_meta_types",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
        ),
    ]
