# Generated by Django 4.2.18 on 2026-03-05 15:21

from django.db import migrations, models
import django.db.models.deletion


def remove_orphaned_eve_type_rows(apps, schema_editor):
    BasePrice = apps.get_model("wizardindustry", "BasePrice")
    InvMetaTypes = apps.get_model("wizardindustry", "invMetaTypes")
    ItemType = apps.get_model("eve_sde", "ItemType")

    valid_item_type_ids = ItemType.objects.values_list("id", flat=True)

    BasePrice.objects.exclude(eve_type_id__in=valid_item_type_ids).delete()
    InvMetaTypes.objects.exclude(eve_type_id__in=valid_item_type_ids).delete()


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
        ("wizardindustry", "0004_invmetatypes"),
    ]

    operations = [
        migrations.RunPython(remove_orphaned_eve_type_rows, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name="baseprice",
            name="eve_type",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wizardindustry_base_price",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="invmetatypes",
            name="eve_type",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inv_meta_types",
                to="eve_sde.itemtype",
            ),
        ),
    ]
