# Generated by Django 4.2.18 on 2025-08-22 13:30

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveuniverse", "0010_alter_eveindustryactivityduration_eve_type_and_more"),
        ("authentication", "0024_alter_userprofile_language"),
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("wizardindustry", "0005_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="corporation_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EveLocation",
            fields=[
                (
                    "location_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eveuniverse.evesolarsystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorporationAsset",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("blueprint_copy", models.BooleanField(default=None, null=True)),
                ("singleton", models.BooleanField()),
                ("item_id", models.BigIntegerField()),
                ("location_flag", models.CharField(max_length=50)),
                ("location_id", models.BigIntegerField()),
                ("location_type", models.CharField(max_length=25)),
                ("quantity", models.IntegerField()),
                ("type_id", models.IntegerField()),
                ("name", models.CharField(default=None, max_length=255, null=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "location_name",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wizardindustry.evelocation",
                    ),
                ),
                (
                    "type_name",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["location_id"], name="wizardindus_locatio_c5349d_idx"
                    ),
                    models.Index(
                        fields=["item_id"], name="wizardindus_item_id_bc42d4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterAsset",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("blueprint_copy", models.BooleanField(default=None, null=True)),
                ("singleton", models.BooleanField()),
                ("item_id", models.BigIntegerField()),
                ("location_flag", models.CharField(max_length=50)),
                ("location_id", models.BigIntegerField()),
                ("location_type", models.CharField(max_length=25)),
                ("quantity", models.IntegerField()),
                ("type_id", models.IntegerField()),
                ("name", models.CharField(default=None, max_length=255, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="authentication.characterownership",
                    ),
                ),
                (
                    "location_name",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wizardindustry.evelocation",
                    ),
                ),
                (
                    "type_name",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["location_id"], name="wizardindus_locatio_7dab8a_idx"
                    ),
                    models.Index(
                        fields=["item_id"], name="wizardindus_item_id_6307c9_idx"
                    ),
                ],
            },
        ),
    ]
