# Generated by Django 4.2.18 on 2026-03-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("wizardindustry", "0001_initial"),
        ("wizardindustry", "0002_alter_baseprice_price"),
        ("wizardindustry", "0003_remove_baseprice_price_baseprice_base_price"),
        ("wizardindustry", "0004_invmetatypes"),
        ("wizardindustry", "0005_alter_baseprice_eve_type_alter_invmetatypes_eve_type"),
    ]

    dependencies = [
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="invMetaTypes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_type_id", models.IntegerField(blank=True, null=True)),
                ("meta_group_id", models.IntegerField(blank=True, null=True)),
                (
                    "eve_type",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inv_meta_types",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BasePrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "eve_type",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wizardindustry_base_price",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
        ),
    ]
