# Generated by Django 4.2.18 on 2026-03-06 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wizardindustry", "0006_initialUpdated"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterBlueprintSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField(db_index=True)),
                ("character_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wizardindustry_blueprint_syncs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "character_id"),
                        name="wizind_chbsync_user_char_unique",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="CharacterBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField(db_index=True)),
                ("character_name", models.CharField(blank=True, max_length=255, null=True)),
                ("item_id", models.BigIntegerField()),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("runs", models.IntegerField(blank=True, null=True)),
                ("material_efficiency", models.IntegerField(blank=True, null=True)),
                ("time_efficiency", models.IntegerField(blank=True, null=True)),
                ("location_id", models.BigIntegerField(blank=True, null=True)),
                ("location_flag", models.CharField(blank=True, max_length=100, null=True)),
                ("is_original", models.BooleanField(db_index=True, default=False)),
                ("last_synced_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "eve_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wizardindustry_blueprint_owners",
                        to="eve_sde.itemtype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wizardindustry_character_blueprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="characterblueprint",
            constraint=models.UniqueConstraint(
                fields=("character_id", "item_id"),
                name="wizind_charbp_item_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="characterblueprint",
            index=models.Index(
                fields=["user", "character_id"],
                name="wizind_charbp_user_char_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="characterblueprint",
            index=models.Index(
                fields=["user", "eve_type", "is_original"],
                name="wizind_charbp_owned_idx",
            ),
        ),
    ]
