# Generated by Django 4.2.18 on 2025-08-22 14:03

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wizardindustry",
            "0006_owner_corporation_owner_evelocation_corporationasset_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterasset",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="corporationasset",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
