# Generated by Django 4.2.18 on 2026-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wizardindustry", "0008_corporationblueprint_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterblueprint",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="characterblueprintsync",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="corporationblueprint",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="corporationblueprintsync",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
