# Generated by Django 4.2.18 on 2025-09-30 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("wizardindustry", "0008_corporationindustryjob_characterindustryjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporationAdmin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_users",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="wizardIndustryCorporationAdmins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="wizardIndustryCorporationUsers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
