# Generated by Django 4.2.27 on 2026-01-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0011_extend_industry_activites'),
        ('wizardindustry', '0008_corporationindustryjob_characterindustryjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterasset',
            name='system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveuniverse.evesolarsystem'),
        ),
        migrations.AddField(
            model_name='corporationasset',
            name='system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveuniverse.evesolarsystem'),
        ),
    ]
