# Generated by Django 4.2.18 on 2026-03-26 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wizardindustry", "0009_alter_characterblueprint_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="characterblueprint",
            options={
                "permissions": [("basic_access", "Can access Wizard Industry")],
            },
        ),
    ]
