# Generated by Django 4.2.18 on 2026-04-08 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wizardindustry", "0010_characterblueprint_basic_access_permission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invmetatypes",
            name="eve_type",
        ),
        migrations.DeleteModel(
            name="BasePrice",
        ),
        migrations.DeleteModel(
            name="invMetaTypes",
        ),
    ]
